[general]
pallet = 1
scale = 3
;output = ./images

[serial]
;port = COM1
baudrate = 115200
; 5, 6, 7, or 8
bytesize = 8
; N = None, O = Odd, E = Even
parity = N
; 1, 1.5, or 2
stopbits = 1

[printer]
; Printer profile. Available profiles can be found here: https://python-escpos.readthedocs.io/en/latest/printer_profiles/available-profiles.html
profile = TM-T88V
; Types can be USB, SERIAL, NETWORK. FILE, or DUMMY
type = FILE
file = /Users/EricHeinke/PycharmProjects/gameboy-thermal-receipt-printer/print_file.txt

; USB: USB address of the printer (vendor ID and product ID)
;vendorID = 0x0000
;productID = 0x0000
;timeout = 0

; SERIAL: Serial device info
;device = /dev/tty.usbserial
;baudrate = 9600
;bytesize = 8
;parity = N
;stopbits = 1
;timeout = 1.00
;xonxoff = False
;dsrdtr = True

; NETWORK: IP address or host name of the printer and port number
;host = 192.168.0.0
;port = 9100
;timeout = 60

; FILE: "prints" to a file
;file = ./printer_output.txt
;autoFlush = True
